---
RecipeFormatVersion: '2020-01-25'
ComponentName: com.invensense.cloud
ComponentVersion: '1.0.0'
ComponentDescription: 'A basic component that runs a simple pub/sub ROS2 application'
ComponentPublisher: InvenSense
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: ~2.0.0
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ~2.0.0
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.example.PubSubPublisher:pubsub:1:
          policyDescription: "Allows access to publish and subscribe to MQTT topics."
          operations:
            - "aws.greengrass#PublishToIoTCore"
            - "aws.greengrass#SubscribeToIoTCore"
          resources:
            - tdk_robokit_icm42622_py
            - tdk_robokit_ch101_py
            - tdk_robokit_ak09918
            - tdk_robokit_ics43434
            - tdk_robokit_icp10101
            - tdk_robokit_ads7052
            - tdk_robokit_camera_py
            - tdk_robokit_lidar_py
            - cloud_tdk_robokit_icm42622_py
            - cloud_tdk_robokit_ch101_py
            - cloud_tdk_robokit_ak09918
            - cloud_tdk_robokit_ics43434
            - cloud_tdk_robokit_icp10101
            - cloud_tdk_robokit_ads7052
            - cloud_tdk_robokit_camera_py
            - cloud_tdk_robokit_lidar_py
Manifests:
  - Platform:
      os: all
    Lifecycle:
      Install: |-
        docker tag 771899563211.dkr.ecr.us-east-2.amazonaws.com/invensense-ros2-cloud:latest invensense-ros2-cloud:latest
      Startup: |
        docker-compose -f {artifacts:path}/docker-compose.yaml up -d
      Shutdown: |
        docker-compose -f {artifacts:path}/docker-compose.yaml down
    Artifacts:
      - URI: "docker:771899563211.dkr.ecr.us-east-2.amazonaws.com/invensense-ros2-cloud:latest"
      - URI: "s3://invensense-stack-s3bucket-1b87o2hmv4hq1/com.invensense.cloud/1.0.0/artifacts/docker-compose.yaml"
