version: "3"
services: 

  greengrass_demo_image:
    build: 
        context: ./
    image: invensense-ros2-cloud:latest

  greengrass_bridge:
    image: invensense-ros2-cloud:latest
    command: ros2 launch greengrass_bridge greengrass_bridge.launch.py ros_topics:="['chatter']" iot_topics:="['cloud_chatter']"
    environment:
      - AWS_REGION
      - SVCUID
      - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT
      - AWS_CONTAINER_AUTHORIZATION_TOKEN
      - AWS_CONTAINER_CREDENTIALS_FULL_URI
    volumes: 
      - "/greengrass/v2/ipc.socket:/greengrass/v2/ipc.socket"
